/*
* generated by Xtext
*/
package org.eclipselabs.emf.scaffolding.language.parser.antlr;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import org.eclipselabs.emf.scaffolding.language.services.EMFScaffoldingDSLGrammarAccess;

public class EMFScaffoldingDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EMFScaffoldingDSLGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, CharStream in) {
		TokenSource tokenSource = createLexer(in);
		XtextTokenStream tokenStream = createTokenStream(tokenSource);
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.eclipselabs.emf.scaffolding.language.parser.antlr.internal.InternalEMFScaffoldingDSLParser parser = createParser(tokenStream);
		parser.setTokenTypeMap(getTokenDefProvider().getTokenDefMap());
		parser.setSyntaxErrorProvider(getSyntaxErrorProvider());
		parser.setUnorderedGroupHelper(getUnorderedGroupHelper().get());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	protected org.eclipselabs.emf.scaffolding.language.parser.antlr.internal.InternalEMFScaffoldingDSLParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.emf.scaffolding.language.parser.antlr.internal.InternalEMFScaffoldingDSLParser(stream, getElementFactory(), getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Scaffolding";
	}
	
	public EMFScaffoldingDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EMFScaffoldingDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
