/*
* generated by Xtext
*/
package org.eclipselabs.emf.scaffolding.language.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipselabs.emf.scaffolding.language.services.EMFScaffoldingDSLGrammarAccess;

public class EMFScaffoldingDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private EMFScaffoldingDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipselabs.emf.scaffolding.language.ui.contentassist.antlr.internal.InternalEMFScaffoldingDSLParser createParser() {
		org.eclipselabs.emf.scaffolding.language.ui.contentassist.antlr.internal.InternalEMFScaffoldingDSLParser result = new org.eclipselabs.emf.scaffolding.language.ui.contentassist.antlr.internal.InternalEMFScaffoldingDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getScaffoldingElementAccess().getAlternatives(), "rule__ScaffoldingElement__Alternatives");
					put(grammarAccess.getWhenBlockAccess().getAlternatives_1(), "rule__WhenBlock__Alternatives_1");
					put(grammarAccess.getBindingAccess().getAlternatives(), "rule__Binding__Alternatives");
					put(grammarAccess.getBindingExpressionAccess().getOpAlternatives_1_1_0(), "rule__BindingExpression__OpAlternatives_1_1_0");
					put(grammarAccess.getBindingTerminalExpressionAccess().getAlternatives(), "rule__BindingTerminalExpression__Alternatives");
					put(grammarAccess.getThenBlockAccess().getAlternatives_0(), "rule__ThenBlock__Alternatives_0");
					put(grammarAccess.getThenBlockAccess().getAlternatives_1(), "rule__ThenBlock__Alternatives_1");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getSetterAccess().getAlternatives_1(), "rule__Setter__Alternatives_1");
					put(grammarAccess.getExpressionAccess().getOpAlternatives_1_1_0(), "rule__Expression__OpAlternatives_1_1_0");
					put(grammarAccess.getTerminalExpressionAccess().getAlternatives(), "rule__TerminalExpression__Alternatives");
					put(grammarAccess.getScaffoldingAccess().getGroup(), "rule__Scaffolding__Group__0");
					put(grammarAccess.getScaffoldAccess().getGroup(), "rule__Scaffold__Group__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getWhenBlockAccess().getGroup(), "rule__WhenBlock__Group__0");
					put(grammarAccess.getWhenBlockAccess().getGroup_1_0(), "rule__WhenBlock__Group_1_0__0");
					put(grammarAccess.getMatchAccess().getGroup(), "rule__Match__Group__0");
					put(grammarAccess.getMatchAccess().getGroup_0(), "rule__Match__Group_0__0");
					put(grammarAccess.getMatchAccess().getGroup_2(), "rule__Match__Group_2__0");
					put(grammarAccess.getMatchAccess().getGroup_2_1(), "rule__Match__Group_2_1__0");
					put(grammarAccess.getMatchAccess().getGroup_2_1_1(), "rule__Match__Group_2_1_1__0");
					put(grammarAccess.getParamAccess().getGroup(), "rule__Param__Group__0");
					put(grammarAccess.getParamAccess().getGroup_1(), "rule__Param__Group_1__0");
					put(grammarAccess.getBindingExpressionAccess().getGroup(), "rule__BindingExpression__Group__0");
					put(grammarAccess.getBindingExpressionAccess().getGroup_1(), "rule__BindingExpression__Group_1__0");
					put(grammarAccess.getBindingTerminalExpressionAccess().getGroup_0(), "rule__BindingTerminalExpression__Group_0__0");
					put(grammarAccess.getBindingTerminalExpressionAccess().getGroup_5(), "rule__BindingTerminalExpression__Group_5__0");
					put(grammarAccess.getBindingTerminalExpressionAccess().getGroup_5_2(), "rule__BindingTerminalExpression__Group_5_2__0");
					put(grammarAccess.getBindingTerminalExpressionAccess().getGroup_6(), "rule__BindingTerminalExpression__Group_6__0");
					put(grammarAccess.getThenBlockAccess().getGroup(), "rule__ThenBlock__Group__0");
					put(grammarAccess.getThenBlockAccess().getGroup_1_0(), "rule__ThenBlock__Group_1_0__0");
					put(grammarAccess.getCreateStatementAccess().getGroup(), "rule__CreateStatement__Group__0");
					put(grammarAccess.getCreateStatementAccess().getGroup_0(), "rule__CreateStatement__Group_0__0");
					put(grammarAccess.getCreateClassAccess().getGroup(), "rule__CreateClass__Group__0");
					put(grammarAccess.getCreateClassAccess().getGroup_2(), "rule__CreateClass__Group_2__0");
					put(grammarAccess.getCreateClassAccess().getGroup_2_1(), "rule__CreateClass__Group_2_1__0");
					put(grammarAccess.getCreateClassAccess().getGroup_2_1_1(), "rule__CreateClass__Group_2_1_1__0");
					put(grammarAccess.getListLiteralAccess().getGroup(), "rule__ListLiteral__Group__0");
					put(grammarAccess.getListLiteralAccess().getGroup_1(), "rule__ListLiteral__Group_1__0");
					put(grammarAccess.getListLiteralAccess().getGroup_1_1(), "rule__ListLiteral__Group_1_1__0");
					put(grammarAccess.getVarRefLiteralAccess().getGroup(), "rule__VarRefLiteral__Group__0");
					put(grammarAccess.getSetterAccess().getGroup(), "rule__Setter__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_0(), "rule__TerminalExpression__Group_0__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_6(), "rule__TerminalExpression__Group_6__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_6_2(), "rule__TerminalExpression__Group_6_2__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_7(), "rule__TerminalExpression__Group_7__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getUpdateStatementAccess().getGroup(), "rule__UpdateStatement__Group__0");
					put(grammarAccess.getUpdateStatementAccess().getGroup_2(), "rule__UpdateStatement__Group_2__0");
					put(grammarAccess.getUpdateStatementAccess().getGroup_2_1(), "rule__UpdateStatement__Group_2_1__0");
					put(grammarAccess.getUpdateStatementAccess().getGroup_2_1_1(), "rule__UpdateStatement__Group_2_1_1__0");
					put(grammarAccess.getClassFqnAccess().getGroup(), "rule__ClassFqn__Group__0");
					put(grammarAccess.getClassFqnAccess().getGroup_1(), "rule__ClassFqn__Group_1__0");
					put(grammarAccess.getScaffoldingAccess().getScaffoldAssignment_0(), "rule__Scaffolding__ScaffoldAssignment_0");
					put(grammarAccess.getScaffoldingAccess().getElementsAssignment_1(), "rule__Scaffolding__ElementsAssignment_1");
					put(grammarAccess.getScaffoldAccess().getRefPackageAssignment_1(), "rule__Scaffold__RefPackageAssignment_1");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getWhenAssignment_2(), "rule__Rule__WhenAssignment_2");
					put(grammarAccess.getRuleAccess().getThenAssignment_3(), "rule__Rule__ThenAssignment_3");
					put(grammarAccess.getWhenBlockAccess().getMatchesAssignment_1_0_1(), "rule__WhenBlock__MatchesAssignment_1_0_1");
					put(grammarAccess.getWhenBlockAccess().getMatchesAssignment_1_1(), "rule__WhenBlock__MatchesAssignment_1_1");
					put(grammarAccess.getMatchAccess().getVarAssignment_0_0(), "rule__Match__VarAssignment_0_0");
					put(grammarAccess.getMatchAccess().getTypeAssignment_1(), "rule__Match__TypeAssignment_1");
					put(grammarAccess.getMatchAccess().getParamsAssignment_2_1_0(), "rule__Match__ParamsAssignment_2_1_0");
					put(grammarAccess.getMatchAccess().getParamsAssignment_2_1_1_1(), "rule__Match__ParamsAssignment_2_1_1_1");
					put(grammarAccess.getVariableAccess().getNameAssignment(), "rule__Variable__NameAssignment");
					put(grammarAccess.getParamAccess().getPropertyAssignment_0(), "rule__Param__PropertyAssignment_0");
					put(grammarAccess.getParamAccess().getVarAssignment_1_1(), "rule__Param__VarAssignment_1_1");
					put(grammarAccess.getBindingExpressionAccess().getOpAssignment_1_1(), "rule__BindingExpression__OpAssignment_1_1");
					put(grammarAccess.getBindingExpressionAccess().getRightAssignment_1_2(), "rule__BindingExpression__RightAssignment_1_2");
					put(grammarAccess.getBindingTerminalExpressionAccess().getFunctionAssignment_5_1(), "rule__BindingTerminalExpression__FunctionAssignment_5_1");
					put(grammarAccess.getBindingTerminalExpressionAccess().getExpAssignment_5_2_1(), "rule__BindingTerminalExpression__ExpAssignment_5_2_1");
					put(grammarAccess.getBindingTerminalExpressionAccess().getValueAssignment_6_1(), "rule__BindingTerminalExpression__ValueAssignment_6_1");
					put(grammarAccess.getFeatureRefLiteralAccess().getRefAssignment(), "rule__FeatureRefLiteral__RefAssignment");
					put(grammarAccess.getThenBlockAccess().getStatementsAssignment_1_0_1(), "rule__ThenBlock__StatementsAssignment_1_0_1");
					put(grammarAccess.getThenBlockAccess().getStatementsAssignment_1_1(), "rule__ThenBlock__StatementsAssignment_1_1");
					put(grammarAccess.getCreateStatementAccess().getVarAssignment_0_0(), "rule__CreateStatement__VarAssignment_0_0");
					put(grammarAccess.getCreateStatementAccess().getExpressionAssignment_1(), "rule__CreateStatement__ExpressionAssignment_1");
					put(grammarAccess.getCreateClassAccess().getTypeAssignment_1(), "rule__CreateClass__TypeAssignment_1");
					put(grammarAccess.getCreateClassAccess().getSettersAssignment_2_1_0(), "rule__CreateClass__SettersAssignment_2_1_0");
					put(grammarAccess.getCreateClassAccess().getSettersAssignment_2_1_1_1(), "rule__CreateClass__SettersAssignment_2_1_1_1");
					put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
					put(grammarAccess.getListLiteralAccess().getItemsAssignment_1_0(), "rule__ListLiteral__ItemsAssignment_1_0");
					put(grammarAccess.getListLiteralAccess().getItemsAssignment_1_1_1(), "rule__ListLiteral__ItemsAssignment_1_1_1");
					put(grammarAccess.getVarRefLiteralAccess().getVarRefAssignment_1(), "rule__VarRefLiteral__VarRefAssignment_1");
					put(grammarAccess.getSetterAccess().getPropertyAssignment_0(), "rule__Setter__PropertyAssignment_0");
					put(grammarAccess.getSetterAccess().getExpressionAssignment_2(), "rule__Setter__ExpressionAssignment_2");
					put(grammarAccess.getSetterAccess().getGuardAssignment_3(), "rule__Setter__GuardAssignment_3");
					put(grammarAccess.getExpressionAccess().getOpAssignment_1_1(), "rule__Expression__OpAssignment_1_1");
					put(grammarAccess.getExpressionAccess().getRightAssignment_1_2(), "rule__Expression__RightAssignment_1_2");
					put(grammarAccess.getTerminalExpressionAccess().getFunctionAssignment_6_1(), "rule__TerminalExpression__FunctionAssignment_6_1");
					put(grammarAccess.getTerminalExpressionAccess().getExpAssignment_6_2_1(), "rule__TerminalExpression__ExpAssignment_6_2_1");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_7_1(), "rule__TerminalExpression__ValueAssignment_7_1");
					put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
					put(grammarAccess.getFunctionAccess().getJavaClassAssignment_2(), "rule__Function__JavaClassAssignment_2");
					put(grammarAccess.getUpdateStatementAccess().getVarRefAssignment_1(), "rule__UpdateStatement__VarRefAssignment_1");
					put(grammarAccess.getUpdateStatementAccess().getSettersAssignment_2_1_0(), "rule__UpdateStatement__SettersAssignment_2_1_0");
					put(grammarAccess.getUpdateStatementAccess().getSettersAssignment_2_1_1_1(), "rule__UpdateStatement__SettersAssignment_2_1_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipselabs.emf.scaffolding.language.ui.contentassist.antlr.internal.InternalEMFScaffoldingDSLParser typedParser = (org.eclipselabs.emf.scaffolding.language.ui.contentassist.antlr.internal.InternalEMFScaffoldingDSLParser) parser;
			typedParser.entryRuleScaffolding();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EMFScaffoldingDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EMFScaffoldingDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
