
/*
 * generated by Xtext
 */
 
package org.eclipselabs.emf.scaffolding.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class EMFScaffoldingDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipselabs.emf.scaffolding.language.ui.internal.EMFScaffoldingDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipselabs.emf.scaffolding.language.ui.internal.EMFScaffoldingDSLActivator.getInstance().getInjector("org.eclipselabs.emf.scaffolding.language.EMFScaffoldingDSL");
	}
	
}
